/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.datawhisperers.restfulexample.avromodel;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DirectionAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6571109217046067869L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DirectionAvro\",\"namespace\":\"com.datawhisperers.restfulexample.avromodel\",\"fields\":[{\"name\":\"trueNorth\",\"type\":{\"type\":\"string\",\"java-class\":\"java.math.BigDecimal\"}},{\"name\":\"magneticNorth\",\"type\":{\"type\":\"string\",\"java-class\":\"java.math.BigDecimal\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();
static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.DecimalConversion());
  }

  private static final BinaryMessageEncoder<DirectionAvro> ENCODER =
      new BinaryMessageEncoder<DirectionAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DirectionAvro> DECODER =
      new BinaryMessageDecoder<DirectionAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DirectionAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DirectionAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DirectionAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DirectionAvro>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DirectionAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DirectionAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DirectionAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DirectionAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.math.BigDecimal trueNorth;
  @Deprecated public java.math.BigDecimal magneticNorth;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DirectionAvro() {}

  /**
   * All-args constructor.
   * @param trueNorth The new value for trueNorth
   * @param magneticNorth The new value for magneticNorth
   */
  public DirectionAvro(java.math.BigDecimal trueNorth, java.math.BigDecimal magneticNorth) {
    this.trueNorth = trueNorth;
    this.magneticNorth = magneticNorth;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return trueNorth;
    case 1: return magneticNorth;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: trueNorth = (java.math.BigDecimal)value$; break;
    case 1: magneticNorth = (java.math.BigDecimal)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'trueNorth' field.
   * @return The value of the 'trueNorth' field.
   */
  public java.math.BigDecimal getTrueNorth() {
    return trueNorth;
  }


  /**
   * Sets the value of the 'trueNorth' field.
   * @param value the value to set.
   */
  public void setTrueNorth(java.math.BigDecimal value) {
    this.trueNorth = value;
  }

  /**
   * Gets the value of the 'magneticNorth' field.
   * @return The value of the 'magneticNorth' field.
   */
  public java.math.BigDecimal getMagneticNorth() {
    return magneticNorth;
  }


  /**
   * Sets the value of the 'magneticNorth' field.
   * @param value the value to set.
   */
  public void setMagneticNorth(java.math.BigDecimal value) {
    this.magneticNorth = value;
  }

  /**
   * Creates a new DirectionAvro RecordBuilder.
   * @return A new DirectionAvro RecordBuilder
   */
  public static com.datawhisperers.restfulexample.avromodel.DirectionAvro.Builder newBuilder() {
    return new com.datawhisperers.restfulexample.avromodel.DirectionAvro.Builder();
  }

  /**
   * Creates a new DirectionAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DirectionAvro RecordBuilder
   */
  public static com.datawhisperers.restfulexample.avromodel.DirectionAvro.Builder newBuilder(com.datawhisperers.restfulexample.avromodel.DirectionAvro.Builder other) {
    if (other == null) {
      return new com.datawhisperers.restfulexample.avromodel.DirectionAvro.Builder();
    } else {
      return new com.datawhisperers.restfulexample.avromodel.DirectionAvro.Builder(other);
    }
  }

  /**
   * Creates a new DirectionAvro RecordBuilder by copying an existing DirectionAvro instance.
   * @param other The existing instance to copy.
   * @return A new DirectionAvro RecordBuilder
   */
  public static com.datawhisperers.restfulexample.avromodel.DirectionAvro.Builder newBuilder(com.datawhisperers.restfulexample.avromodel.DirectionAvro other) {
    if (other == null) {
      return new com.datawhisperers.restfulexample.avromodel.DirectionAvro.Builder();
    } else {
      return new com.datawhisperers.restfulexample.avromodel.DirectionAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for DirectionAvro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DirectionAvro>
    implements org.apache.avro.data.RecordBuilder<DirectionAvro> {

    private java.math.BigDecimal trueNorth;
    private java.math.BigDecimal magneticNorth;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.datawhisperers.restfulexample.avromodel.DirectionAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.trueNorth)) {
        this.trueNorth = data().deepCopy(fields()[0].schema(), other.trueNorth);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.magneticNorth)) {
        this.magneticNorth = data().deepCopy(fields()[1].schema(), other.magneticNorth);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing DirectionAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.datawhisperers.restfulexample.avromodel.DirectionAvro other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.trueNorth)) {
        this.trueNorth = data().deepCopy(fields()[0].schema(), other.trueNorth);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.magneticNorth)) {
        this.magneticNorth = data().deepCopy(fields()[1].schema(), other.magneticNorth);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'trueNorth' field.
      * @return The value.
      */
    public java.math.BigDecimal getTrueNorth() {
      return trueNorth;
    }


    /**
      * Sets the value of the 'trueNorth' field.
      * @param value The value of 'trueNorth'.
      * @return This builder.
      */
    public com.datawhisperers.restfulexample.avromodel.DirectionAvro.Builder setTrueNorth(java.math.BigDecimal value) {
      validate(fields()[0], value);
      this.trueNorth = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'trueNorth' field has been set.
      * @return True if the 'trueNorth' field has been set, false otherwise.
      */
    public boolean hasTrueNorth() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'trueNorth' field.
      * @return This builder.
      */
    public com.datawhisperers.restfulexample.avromodel.DirectionAvro.Builder clearTrueNorth() {
      trueNorth = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'magneticNorth' field.
      * @return The value.
      */
    public java.math.BigDecimal getMagneticNorth() {
      return magneticNorth;
    }


    /**
      * Sets the value of the 'magneticNorth' field.
      * @param value The value of 'magneticNorth'.
      * @return This builder.
      */
    public com.datawhisperers.restfulexample.avromodel.DirectionAvro.Builder setMagneticNorth(java.math.BigDecimal value) {
      validate(fields()[1], value);
      this.magneticNorth = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'magneticNorth' field has been set.
      * @return True if the 'magneticNorth' field has been set, false otherwise.
      */
    public boolean hasMagneticNorth() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'magneticNorth' field.
      * @return This builder.
      */
    public com.datawhisperers.restfulexample.avromodel.DirectionAvro.Builder clearMagneticNorth() {
      magneticNorth = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DirectionAvro build() {
      try {
        DirectionAvro record = new DirectionAvro();
        record.trueNorth = fieldSetFlags()[0] ? this.trueNorth : (java.math.BigDecimal) defaultValue(fields()[0]);
        record.magneticNorth = fieldSetFlags()[1] ? this.magneticNorth : (java.math.BigDecimal) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DirectionAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<DirectionAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DirectionAvro>
    READER$ = (org.apache.avro.io.DatumReader<DirectionAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.trueNorth.toString());

    out.writeString(this.magneticNorth.toString());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.trueNorth = new java.math.BigDecimal(in.readString());

      this.magneticNorth = new java.math.BigDecimal(in.readString());

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.trueNorth = new java.math.BigDecimal(in.readString());
          break;

        case 1:
          this.magneticNorth = new java.math.BigDecimal(in.readString());
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










