/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.datawhisperers.restfulexample.avromodel;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class GPSAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2562640234889595926L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GPSAvro\",\"namespace\":\"com.datawhisperers.restfulexample.avromodel\",\"fields\":[{\"name\":\"gpsRawPosition\",\"type\":{\"type\":\"record\",\"name\":\"PositionAvro\",\"fields\":[{\"name\":\"lat\",\"type\":{\"type\":\"string\",\"java-class\":\"java.math.BigDecimal\"}},{\"name\":\"lon\",\"type\":{\"type\":\"string\",\"java-class\":\"java.math.BigDecimal\"}},{\"name\":\"numberOfSatellitesAcquired\",\"type\":\"int\"}]}},{\"name\":\"gpsMapMatchPosition\",\"type\":\"PositionAvro\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();
static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.DecimalConversion());
  }

  private static final BinaryMessageEncoder<GPSAvro> ENCODER =
      new BinaryMessageEncoder<GPSAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<GPSAvro> DECODER =
      new BinaryMessageDecoder<GPSAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<GPSAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<GPSAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<GPSAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<GPSAvro>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this GPSAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a GPSAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a GPSAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static GPSAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public com.datawhisperers.restfulexample.avromodel.PositionAvro gpsRawPosition;
  @Deprecated public com.datawhisperers.restfulexample.avromodel.PositionAvro gpsMapMatchPosition;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GPSAvro() {}

  /**
   * All-args constructor.
   * @param gpsRawPosition The new value for gpsRawPosition
   * @param gpsMapMatchPosition The new value for gpsMapMatchPosition
   */
  public GPSAvro(com.datawhisperers.restfulexample.avromodel.PositionAvro gpsRawPosition, com.datawhisperers.restfulexample.avromodel.PositionAvro gpsMapMatchPosition) {
    this.gpsRawPosition = gpsRawPosition;
    this.gpsMapMatchPosition = gpsMapMatchPosition;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return gpsRawPosition;
    case 1: return gpsMapMatchPosition;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: gpsRawPosition = (com.datawhisperers.restfulexample.avromodel.PositionAvro)value$; break;
    case 1: gpsMapMatchPosition = (com.datawhisperers.restfulexample.avromodel.PositionAvro)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'gpsRawPosition' field.
   * @return The value of the 'gpsRawPosition' field.
   */
  public com.datawhisperers.restfulexample.avromodel.PositionAvro getGpsRawPosition() {
    return gpsRawPosition;
  }


  /**
   * Sets the value of the 'gpsRawPosition' field.
   * @param value the value to set.
   */
  public void setGpsRawPosition(com.datawhisperers.restfulexample.avromodel.PositionAvro value) {
    this.gpsRawPosition = value;
  }

  /**
   * Gets the value of the 'gpsMapMatchPosition' field.
   * @return The value of the 'gpsMapMatchPosition' field.
   */
  public com.datawhisperers.restfulexample.avromodel.PositionAvro getGpsMapMatchPosition() {
    return gpsMapMatchPosition;
  }


  /**
   * Sets the value of the 'gpsMapMatchPosition' field.
   * @param value the value to set.
   */
  public void setGpsMapMatchPosition(com.datawhisperers.restfulexample.avromodel.PositionAvro value) {
    this.gpsMapMatchPosition = value;
  }

  /**
   * Creates a new GPSAvro RecordBuilder.
   * @return A new GPSAvro RecordBuilder
   */
  public static com.datawhisperers.restfulexample.avromodel.GPSAvro.Builder newBuilder() {
    return new com.datawhisperers.restfulexample.avromodel.GPSAvro.Builder();
  }

  /**
   * Creates a new GPSAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new GPSAvro RecordBuilder
   */
  public static com.datawhisperers.restfulexample.avromodel.GPSAvro.Builder newBuilder(com.datawhisperers.restfulexample.avromodel.GPSAvro.Builder other) {
    if (other == null) {
      return new com.datawhisperers.restfulexample.avromodel.GPSAvro.Builder();
    } else {
      return new com.datawhisperers.restfulexample.avromodel.GPSAvro.Builder(other);
    }
  }

  /**
   * Creates a new GPSAvro RecordBuilder by copying an existing GPSAvro instance.
   * @param other The existing instance to copy.
   * @return A new GPSAvro RecordBuilder
   */
  public static com.datawhisperers.restfulexample.avromodel.GPSAvro.Builder newBuilder(com.datawhisperers.restfulexample.avromodel.GPSAvro other) {
    if (other == null) {
      return new com.datawhisperers.restfulexample.avromodel.GPSAvro.Builder();
    } else {
      return new com.datawhisperers.restfulexample.avromodel.GPSAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for GPSAvro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GPSAvro>
    implements org.apache.avro.data.RecordBuilder<GPSAvro> {

    private com.datawhisperers.restfulexample.avromodel.PositionAvro gpsRawPosition;
    private com.datawhisperers.restfulexample.avromodel.PositionAvro.Builder gpsRawPositionBuilder;
    private com.datawhisperers.restfulexample.avromodel.PositionAvro gpsMapMatchPosition;
    private com.datawhisperers.restfulexample.avromodel.PositionAvro.Builder gpsMapMatchPositionBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.datawhisperers.restfulexample.avromodel.GPSAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.gpsRawPosition)) {
        this.gpsRawPosition = data().deepCopy(fields()[0].schema(), other.gpsRawPosition);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasGpsRawPositionBuilder()) {
        this.gpsRawPositionBuilder = com.datawhisperers.restfulexample.avromodel.PositionAvro.newBuilder(other.getGpsRawPositionBuilder());
      }
      if (isValidValue(fields()[1], other.gpsMapMatchPosition)) {
        this.gpsMapMatchPosition = data().deepCopy(fields()[1].schema(), other.gpsMapMatchPosition);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (other.hasGpsMapMatchPositionBuilder()) {
        this.gpsMapMatchPositionBuilder = com.datawhisperers.restfulexample.avromodel.PositionAvro.newBuilder(other.getGpsMapMatchPositionBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing GPSAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.datawhisperers.restfulexample.avromodel.GPSAvro other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.gpsRawPosition)) {
        this.gpsRawPosition = data().deepCopy(fields()[0].schema(), other.gpsRawPosition);
        fieldSetFlags()[0] = true;
      }
      this.gpsRawPositionBuilder = null;
      if (isValidValue(fields()[1], other.gpsMapMatchPosition)) {
        this.gpsMapMatchPosition = data().deepCopy(fields()[1].schema(), other.gpsMapMatchPosition);
        fieldSetFlags()[1] = true;
      }
      this.gpsMapMatchPositionBuilder = null;
    }

    /**
      * Gets the value of the 'gpsRawPosition' field.
      * @return The value.
      */
    public com.datawhisperers.restfulexample.avromodel.PositionAvro getGpsRawPosition() {
      return gpsRawPosition;
    }


    /**
      * Sets the value of the 'gpsRawPosition' field.
      * @param value The value of 'gpsRawPosition'.
      * @return This builder.
      */
    public com.datawhisperers.restfulexample.avromodel.GPSAvro.Builder setGpsRawPosition(com.datawhisperers.restfulexample.avromodel.PositionAvro value) {
      validate(fields()[0], value);
      this.gpsRawPositionBuilder = null;
      this.gpsRawPosition = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'gpsRawPosition' field has been set.
      * @return True if the 'gpsRawPosition' field has been set, false otherwise.
      */
    public boolean hasGpsRawPosition() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'gpsRawPosition' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.datawhisperers.restfulexample.avromodel.PositionAvro.Builder getGpsRawPositionBuilder() {
      if (gpsRawPositionBuilder == null) {
        if (hasGpsRawPosition()) {
          setGpsRawPositionBuilder(com.datawhisperers.restfulexample.avromodel.PositionAvro.newBuilder(gpsRawPosition));
        } else {
          setGpsRawPositionBuilder(com.datawhisperers.restfulexample.avromodel.PositionAvro.newBuilder());
        }
      }
      return gpsRawPositionBuilder;
    }

    /**
     * Sets the Builder instance for the 'gpsRawPosition' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.datawhisperers.restfulexample.avromodel.GPSAvro.Builder setGpsRawPositionBuilder(com.datawhisperers.restfulexample.avromodel.PositionAvro.Builder value) {
      clearGpsRawPosition();
      gpsRawPositionBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'gpsRawPosition' field has an active Builder instance
     * @return True if the 'gpsRawPosition' field has an active Builder instance
     */
    public boolean hasGpsRawPositionBuilder() {
      return gpsRawPositionBuilder != null;
    }

    /**
      * Clears the value of the 'gpsRawPosition' field.
      * @return This builder.
      */
    public com.datawhisperers.restfulexample.avromodel.GPSAvro.Builder clearGpsRawPosition() {
      gpsRawPosition = null;
      gpsRawPositionBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'gpsMapMatchPosition' field.
      * @return The value.
      */
    public com.datawhisperers.restfulexample.avromodel.PositionAvro getGpsMapMatchPosition() {
      return gpsMapMatchPosition;
    }


    /**
      * Sets the value of the 'gpsMapMatchPosition' field.
      * @param value The value of 'gpsMapMatchPosition'.
      * @return This builder.
      */
    public com.datawhisperers.restfulexample.avromodel.GPSAvro.Builder setGpsMapMatchPosition(com.datawhisperers.restfulexample.avromodel.PositionAvro value) {
      validate(fields()[1], value);
      this.gpsMapMatchPositionBuilder = null;
      this.gpsMapMatchPosition = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'gpsMapMatchPosition' field has been set.
      * @return True if the 'gpsMapMatchPosition' field has been set, false otherwise.
      */
    public boolean hasGpsMapMatchPosition() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'gpsMapMatchPosition' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.datawhisperers.restfulexample.avromodel.PositionAvro.Builder getGpsMapMatchPositionBuilder() {
      if (gpsMapMatchPositionBuilder == null) {
        if (hasGpsMapMatchPosition()) {
          setGpsMapMatchPositionBuilder(com.datawhisperers.restfulexample.avromodel.PositionAvro.newBuilder(gpsMapMatchPosition));
        } else {
          setGpsMapMatchPositionBuilder(com.datawhisperers.restfulexample.avromodel.PositionAvro.newBuilder());
        }
      }
      return gpsMapMatchPositionBuilder;
    }

    /**
     * Sets the Builder instance for the 'gpsMapMatchPosition' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.datawhisperers.restfulexample.avromodel.GPSAvro.Builder setGpsMapMatchPositionBuilder(com.datawhisperers.restfulexample.avromodel.PositionAvro.Builder value) {
      clearGpsMapMatchPosition();
      gpsMapMatchPositionBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'gpsMapMatchPosition' field has an active Builder instance
     * @return True if the 'gpsMapMatchPosition' field has an active Builder instance
     */
    public boolean hasGpsMapMatchPositionBuilder() {
      return gpsMapMatchPositionBuilder != null;
    }

    /**
      * Clears the value of the 'gpsMapMatchPosition' field.
      * @return This builder.
      */
    public com.datawhisperers.restfulexample.avromodel.GPSAvro.Builder clearGpsMapMatchPosition() {
      gpsMapMatchPosition = null;
      gpsMapMatchPositionBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public GPSAvro build() {
      try {
        GPSAvro record = new GPSAvro();
        if (gpsRawPositionBuilder != null) {
          try {
            record.gpsRawPosition = this.gpsRawPositionBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("gpsRawPosition"));
            throw e;
          }
        } else {
          record.gpsRawPosition = fieldSetFlags()[0] ? this.gpsRawPosition : (com.datawhisperers.restfulexample.avromodel.PositionAvro) defaultValue(fields()[0]);
        }
        if (gpsMapMatchPositionBuilder != null) {
          try {
            record.gpsMapMatchPosition = this.gpsMapMatchPositionBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("gpsMapMatchPosition"));
            throw e;
          }
        } else {
          record.gpsMapMatchPosition = fieldSetFlags()[1] ? this.gpsMapMatchPosition : (com.datawhisperers.restfulexample.avromodel.PositionAvro) defaultValue(fields()[1]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<GPSAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<GPSAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<GPSAvro>
    READER$ = (org.apache.avro.io.DatumReader<GPSAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    this.gpsRawPosition.customEncode(out);

    this.gpsMapMatchPosition.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.gpsRawPosition == null) {
        this.gpsRawPosition = new com.datawhisperers.restfulexample.avromodel.PositionAvro();
      }
      this.gpsRawPosition.customDecode(in);

      if (this.gpsMapMatchPosition == null) {
        this.gpsMapMatchPosition = new com.datawhisperers.restfulexample.avromodel.PositionAvro();
      }
      this.gpsMapMatchPosition.customDecode(in);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.gpsRawPosition == null) {
            this.gpsRawPosition = new com.datawhisperers.restfulexample.avromodel.PositionAvro();
          }
          this.gpsRawPosition.customDecode(in);
          break;

        case 1:
          if (this.gpsMapMatchPosition == null) {
            this.gpsMapMatchPosition = new com.datawhisperers.restfulexample.avromodel.PositionAvro();
          }
          this.gpsMapMatchPosition.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










