/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.datawhisperers.restfulexample.avromodel;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class OEMVehicleDataAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4893580760730248252L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OEMVehicleDataAvro\",\"namespace\":\"com.datawhisperers.restfulexample.avromodel\",\"fields\":[{\"name\":\"accuracy\",\"type\":[\"null\",\"string\"]},{\"name\":\"activityType\",\"type\":[\"null\",\"string\"]},{\"name\":\"direction\",\"type\":{\"type\":\"int\",\"java-class\":\"java.lang.Integer\"}},{\"name\":\"id\",\"type\":[\"null\",\"string\"]},{\"name\":\"position\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"PositionAvro\",\"fields\":[{\"name\":\"lat\",\"type\":[\"null\",{\"type\":\"string\",\"java-class\":\"java.math.BigDecimal\"}]},{\"name\":\"lon\",\"type\":[\"null\",{\"type\":\"string\",\"java-class\":\"java.math.BigDecimal\"}]}]}]},{\"name\":\"speed\",\"type\":{\"type\":\"double\",\"java-class\":\"java.lang.Double\"}},{\"name\":\"timestampEpoch\",\"type\":[\"null\",{\"type\":\"int\",\"java-class\":\"java.lang.Integer\"}]},{\"name\":\"vehicleType\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();
static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.DecimalConversion());
  }

  private static final BinaryMessageEncoder<OEMVehicleDataAvro> ENCODER =
      new BinaryMessageEncoder<OEMVehicleDataAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OEMVehicleDataAvro> DECODER =
      new BinaryMessageDecoder<OEMVehicleDataAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<OEMVehicleDataAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<OEMVehicleDataAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<OEMVehicleDataAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OEMVehicleDataAvro>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this OEMVehicleDataAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a OEMVehicleDataAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a OEMVehicleDataAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static OEMVehicleDataAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence accuracy;
  @Deprecated public java.lang.CharSequence activityType;
  @Deprecated public int direction;
  @Deprecated public java.lang.CharSequence id;
  @Deprecated public com.datawhisperers.restfulexample.avromodel.PositionAvro position;
  @Deprecated public double speed;
  @Deprecated public java.lang.Integer timestampEpoch;
  @Deprecated public java.lang.CharSequence vehicleType;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OEMVehicleDataAvro() {}

  /**
   * All-args constructor.
   * @param accuracy The new value for accuracy
   * @param activityType The new value for activityType
   * @param direction The new value for direction
   * @param id The new value for id
   * @param position The new value for position
   * @param speed The new value for speed
   * @param timestampEpoch The new value for timestampEpoch
   * @param vehicleType The new value for vehicleType
   */
  public OEMVehicleDataAvro(java.lang.CharSequence accuracy, java.lang.CharSequence activityType, java.lang.Integer direction, java.lang.CharSequence id, com.datawhisperers.restfulexample.avromodel.PositionAvro position, java.lang.Double speed, java.lang.Integer timestampEpoch, java.lang.CharSequence vehicleType) {
    this.accuracy = accuracy;
    this.activityType = activityType;
    this.direction = direction;
    this.id = id;
    this.position = position;
    this.speed = speed;
    this.timestampEpoch = timestampEpoch;
    this.vehicleType = vehicleType;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return accuracy;
    case 1: return activityType;
    case 2: return direction;
    case 3: return id;
    case 4: return position;
    case 5: return speed;
    case 6: return timestampEpoch;
    case 7: return vehicleType;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: accuracy = (java.lang.CharSequence)value$; break;
    case 1: activityType = (java.lang.CharSequence)value$; break;
    case 2: direction = (java.lang.Integer)value$; break;
    case 3: id = (java.lang.CharSequence)value$; break;
    case 4: position = (com.datawhisperers.restfulexample.avromodel.PositionAvro)value$; break;
    case 5: speed = (java.lang.Double)value$; break;
    case 6: timestampEpoch = (java.lang.Integer)value$; break;
    case 7: vehicleType = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'accuracy' field.
   * @return The value of the 'accuracy' field.
   */
  public java.lang.CharSequence getAccuracy() {
    return accuracy;
  }


  /**
   * Sets the value of the 'accuracy' field.
   * @param value the value to set.
   */
  public void setAccuracy(java.lang.CharSequence value) {
    this.accuracy = value;
  }

  /**
   * Gets the value of the 'activityType' field.
   * @return The value of the 'activityType' field.
   */
  public java.lang.CharSequence getActivityType() {
    return activityType;
  }


  /**
   * Sets the value of the 'activityType' field.
   * @param value the value to set.
   */
  public void setActivityType(java.lang.CharSequence value) {
    this.activityType = value;
  }

  /**
   * Gets the value of the 'direction' field.
   * @return The value of the 'direction' field.
   */
  public int getDirection() {
    return direction;
  }


  /**
   * Sets the value of the 'direction' field.
   * @param value the value to set.
   */
  public void setDirection(int value) {
    this.direction = value;
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'position' field.
   * @return The value of the 'position' field.
   */
  public com.datawhisperers.restfulexample.avromodel.PositionAvro getPosition() {
    return position;
  }


  /**
   * Sets the value of the 'position' field.
   * @param value the value to set.
   */
  public void setPosition(com.datawhisperers.restfulexample.avromodel.PositionAvro value) {
    this.position = value;
  }

  /**
   * Gets the value of the 'speed' field.
   * @return The value of the 'speed' field.
   */
  public double getSpeed() {
    return speed;
  }


  /**
   * Sets the value of the 'speed' field.
   * @param value the value to set.
   */
  public void setSpeed(double value) {
    this.speed = value;
  }

  /**
   * Gets the value of the 'timestampEpoch' field.
   * @return The value of the 'timestampEpoch' field.
   */
  public java.lang.Integer getTimestampEpoch() {
    return timestampEpoch;
  }


  /**
   * Sets the value of the 'timestampEpoch' field.
   * @param value the value to set.
   */
  public void setTimestampEpoch(java.lang.Integer value) {
    this.timestampEpoch = value;
  }

  /**
   * Gets the value of the 'vehicleType' field.
   * @return The value of the 'vehicleType' field.
   */
  public java.lang.CharSequence getVehicleType() {
    return vehicleType;
  }


  /**
   * Sets the value of the 'vehicleType' field.
   * @param value the value to set.
   */
  public void setVehicleType(java.lang.CharSequence value) {
    this.vehicleType = value;
  }

  /**
   * Creates a new OEMVehicleDataAvro RecordBuilder.
   * @return A new OEMVehicleDataAvro RecordBuilder
   */
  public static com.datawhisperers.restfulexample.avromodel.OEMVehicleDataAvro.Builder newBuilder() {
    return new com.datawhisperers.restfulexample.avromodel.OEMVehicleDataAvro.Builder();
  }

  /**
   * Creates a new OEMVehicleDataAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OEMVehicleDataAvro RecordBuilder
   */
  public static com.datawhisperers.restfulexample.avromodel.OEMVehicleDataAvro.Builder newBuilder(com.datawhisperers.restfulexample.avromodel.OEMVehicleDataAvro.Builder other) {
    if (other == null) {
      return new com.datawhisperers.restfulexample.avromodel.OEMVehicleDataAvro.Builder();
    } else {
      return new com.datawhisperers.restfulexample.avromodel.OEMVehicleDataAvro.Builder(other);
    }
  }

  /**
   * Creates a new OEMVehicleDataAvro RecordBuilder by copying an existing OEMVehicleDataAvro instance.
   * @param other The existing instance to copy.
   * @return A new OEMVehicleDataAvro RecordBuilder
   */
  public static com.datawhisperers.restfulexample.avromodel.OEMVehicleDataAvro.Builder newBuilder(com.datawhisperers.restfulexample.avromodel.OEMVehicleDataAvro other) {
    if (other == null) {
      return new com.datawhisperers.restfulexample.avromodel.OEMVehicleDataAvro.Builder();
    } else {
      return new com.datawhisperers.restfulexample.avromodel.OEMVehicleDataAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for OEMVehicleDataAvro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OEMVehicleDataAvro>
    implements org.apache.avro.data.RecordBuilder<OEMVehicleDataAvro> {

    private java.lang.CharSequence accuracy;
    private java.lang.CharSequence activityType;
    private int direction;
    private java.lang.CharSequence id;
    private com.datawhisperers.restfulexample.avromodel.PositionAvro position;
    private com.datawhisperers.restfulexample.avromodel.PositionAvro.Builder positionBuilder;
    private double speed;
    private java.lang.Integer timestampEpoch;
    private java.lang.CharSequence vehicleType;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.datawhisperers.restfulexample.avromodel.OEMVehicleDataAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.accuracy)) {
        this.accuracy = data().deepCopy(fields()[0].schema(), other.accuracy);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.activityType)) {
        this.activityType = data().deepCopy(fields()[1].schema(), other.activityType);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.direction)) {
        this.direction = data().deepCopy(fields()[2].schema(), other.direction);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.id)) {
        this.id = data().deepCopy(fields()[3].schema(), other.id);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.position)) {
        this.position = data().deepCopy(fields()[4].schema(), other.position);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (other.hasPositionBuilder()) {
        this.positionBuilder = com.datawhisperers.restfulexample.avromodel.PositionAvro.newBuilder(other.getPositionBuilder());
      }
      if (isValidValue(fields()[5], other.speed)) {
        this.speed = data().deepCopy(fields()[5].schema(), other.speed);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.timestampEpoch)) {
        this.timestampEpoch = data().deepCopy(fields()[6].schema(), other.timestampEpoch);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.vehicleType)) {
        this.vehicleType = data().deepCopy(fields()[7].schema(), other.vehicleType);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing OEMVehicleDataAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.datawhisperers.restfulexample.avromodel.OEMVehicleDataAvro other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.accuracy)) {
        this.accuracy = data().deepCopy(fields()[0].schema(), other.accuracy);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.activityType)) {
        this.activityType = data().deepCopy(fields()[1].schema(), other.activityType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.direction)) {
        this.direction = data().deepCopy(fields()[2].schema(), other.direction);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.id)) {
        this.id = data().deepCopy(fields()[3].schema(), other.id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.position)) {
        this.position = data().deepCopy(fields()[4].schema(), other.position);
        fieldSetFlags()[4] = true;
      }
      this.positionBuilder = null;
      if (isValidValue(fields()[5], other.speed)) {
        this.speed = data().deepCopy(fields()[5].schema(), other.speed);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.timestampEpoch)) {
        this.timestampEpoch = data().deepCopy(fields()[6].schema(), other.timestampEpoch);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.vehicleType)) {
        this.vehicleType = data().deepCopy(fields()[7].schema(), other.vehicleType);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'accuracy' field.
      * @return The value.
      */
    public java.lang.CharSequence getAccuracy() {
      return accuracy;
    }


    /**
      * Sets the value of the 'accuracy' field.
      * @param value The value of 'accuracy'.
      * @return This builder.
      */
    public com.datawhisperers.restfulexample.avromodel.OEMVehicleDataAvro.Builder setAccuracy(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.accuracy = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'accuracy' field has been set.
      * @return True if the 'accuracy' field has been set, false otherwise.
      */
    public boolean hasAccuracy() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'accuracy' field.
      * @return This builder.
      */
    public com.datawhisperers.restfulexample.avromodel.OEMVehicleDataAvro.Builder clearAccuracy() {
      accuracy = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'activityType' field.
      * @return The value.
      */
    public java.lang.CharSequence getActivityType() {
      return activityType;
    }


    /**
      * Sets the value of the 'activityType' field.
      * @param value The value of 'activityType'.
      * @return This builder.
      */
    public com.datawhisperers.restfulexample.avromodel.OEMVehicleDataAvro.Builder setActivityType(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.activityType = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'activityType' field has been set.
      * @return True if the 'activityType' field has been set, false otherwise.
      */
    public boolean hasActivityType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'activityType' field.
      * @return This builder.
      */
    public com.datawhisperers.restfulexample.avromodel.OEMVehicleDataAvro.Builder clearActivityType() {
      activityType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'direction' field.
      * @return The value.
      */
    public int getDirection() {
      return direction;
    }


    /**
      * Sets the value of the 'direction' field.
      * @param value The value of 'direction'.
      * @return This builder.
      */
    public com.datawhisperers.restfulexample.avromodel.OEMVehicleDataAvro.Builder setDirection(int value) {
      validate(fields()[2], value);
      this.direction = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'direction' field has been set.
      * @return True if the 'direction' field has been set, false otherwise.
      */
    public boolean hasDirection() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'direction' field.
      * @return This builder.
      */
    public com.datawhisperers.restfulexample.avromodel.OEMVehicleDataAvro.Builder clearDirection() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.datawhisperers.restfulexample.avromodel.OEMVehicleDataAvro.Builder setId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.id = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.datawhisperers.restfulexample.avromodel.OEMVehicleDataAvro.Builder clearId() {
      id = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'position' field.
      * @return The value.
      */
    public com.datawhisperers.restfulexample.avromodel.PositionAvro getPosition() {
      return position;
    }


    /**
      * Sets the value of the 'position' field.
      * @param value The value of 'position'.
      * @return This builder.
      */
    public com.datawhisperers.restfulexample.avromodel.OEMVehicleDataAvro.Builder setPosition(com.datawhisperers.restfulexample.avromodel.PositionAvro value) {
      validate(fields()[4], value);
      this.positionBuilder = null;
      this.position = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'position' field has been set.
      * @return True if the 'position' field has been set, false otherwise.
      */
    public boolean hasPosition() {
      return fieldSetFlags()[4];
    }

    /**
     * Gets the Builder instance for the 'position' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.datawhisperers.restfulexample.avromodel.PositionAvro.Builder getPositionBuilder() {
      if (positionBuilder == null) {
        if (hasPosition()) {
          setPositionBuilder(com.datawhisperers.restfulexample.avromodel.PositionAvro.newBuilder(position));
        } else {
          setPositionBuilder(com.datawhisperers.restfulexample.avromodel.PositionAvro.newBuilder());
        }
      }
      return positionBuilder;
    }

    /**
     * Sets the Builder instance for the 'position' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.datawhisperers.restfulexample.avromodel.OEMVehicleDataAvro.Builder setPositionBuilder(com.datawhisperers.restfulexample.avromodel.PositionAvro.Builder value) {
      clearPosition();
      positionBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'position' field has an active Builder instance
     * @return True if the 'position' field has an active Builder instance
     */
    public boolean hasPositionBuilder() {
      return positionBuilder != null;
    }

    /**
      * Clears the value of the 'position' field.
      * @return This builder.
      */
    public com.datawhisperers.restfulexample.avromodel.OEMVehicleDataAvro.Builder clearPosition() {
      position = null;
      positionBuilder = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'speed' field.
      * @return The value.
      */
    public double getSpeed() {
      return speed;
    }


    /**
      * Sets the value of the 'speed' field.
      * @param value The value of 'speed'.
      * @return This builder.
      */
    public com.datawhisperers.restfulexample.avromodel.OEMVehicleDataAvro.Builder setSpeed(double value) {
      validate(fields()[5], value);
      this.speed = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'speed' field has been set.
      * @return True if the 'speed' field has been set, false otherwise.
      */
    public boolean hasSpeed() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'speed' field.
      * @return This builder.
      */
    public com.datawhisperers.restfulexample.avromodel.OEMVehicleDataAvro.Builder clearSpeed() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestampEpoch' field.
      * @return The value.
      */
    public java.lang.Integer getTimestampEpoch() {
      return timestampEpoch;
    }


    /**
      * Sets the value of the 'timestampEpoch' field.
      * @param value The value of 'timestampEpoch'.
      * @return This builder.
      */
    public com.datawhisperers.restfulexample.avromodel.OEMVehicleDataAvro.Builder setTimestampEpoch(java.lang.Integer value) {
      validate(fields()[6], value);
      this.timestampEpoch = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'timestampEpoch' field has been set.
      * @return True if the 'timestampEpoch' field has been set, false otherwise.
      */
    public boolean hasTimestampEpoch() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'timestampEpoch' field.
      * @return This builder.
      */
    public com.datawhisperers.restfulexample.avromodel.OEMVehicleDataAvro.Builder clearTimestampEpoch() {
      timestampEpoch = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'vehicleType' field.
      * @return The value.
      */
    public java.lang.CharSequence getVehicleType() {
      return vehicleType;
    }


    /**
      * Sets the value of the 'vehicleType' field.
      * @param value The value of 'vehicleType'.
      * @return This builder.
      */
    public com.datawhisperers.restfulexample.avromodel.OEMVehicleDataAvro.Builder setVehicleType(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.vehicleType = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'vehicleType' field has been set.
      * @return True if the 'vehicleType' field has been set, false otherwise.
      */
    public boolean hasVehicleType() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'vehicleType' field.
      * @return This builder.
      */
    public com.datawhisperers.restfulexample.avromodel.OEMVehicleDataAvro.Builder clearVehicleType() {
      vehicleType = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OEMVehicleDataAvro build() {
      try {
        OEMVehicleDataAvro record = new OEMVehicleDataAvro();
        record.accuracy = fieldSetFlags()[0] ? this.accuracy : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.activityType = fieldSetFlags()[1] ? this.activityType : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.direction = fieldSetFlags()[2] ? this.direction : (java.lang.Integer) defaultValue(fields()[2]);
        record.id = fieldSetFlags()[3] ? this.id : (java.lang.CharSequence) defaultValue(fields()[3]);
        if (positionBuilder != null) {
          try {
            record.position = this.positionBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("position"));
            throw e;
          }
        } else {
          record.position = fieldSetFlags()[4] ? this.position : (com.datawhisperers.restfulexample.avromodel.PositionAvro) defaultValue(fields()[4]);
        }
        record.speed = fieldSetFlags()[5] ? this.speed : (java.lang.Double) defaultValue(fields()[5]);
        record.timestampEpoch = fieldSetFlags()[6] ? this.timestampEpoch : (java.lang.Integer) defaultValue(fields()[6]);
        record.vehicleType = fieldSetFlags()[7] ? this.vehicleType : (java.lang.CharSequence) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OEMVehicleDataAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<OEMVehicleDataAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OEMVehicleDataAvro>
    READER$ = (org.apache.avro.io.DatumReader<OEMVehicleDataAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.accuracy == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.accuracy);
    }

    if (this.activityType == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.activityType);
    }

    out.writeInt(this.direction);

    if (this.id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.id);
    }

    if (this.position == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.position.customEncode(out);
    }

    out.writeDouble(this.speed);

    if (this.timestampEpoch == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.timestampEpoch);
    }

    if (this.vehicleType == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.vehicleType);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.accuracy = null;
      } else {
        this.accuracy = in.readString(this.accuracy instanceof Utf8 ? (Utf8)this.accuracy : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.activityType = null;
      } else {
        this.activityType = in.readString(this.activityType instanceof Utf8 ? (Utf8)this.activityType : null);
      }

      this.direction = in.readInt();

      if (in.readIndex() != 1) {
        in.readNull();
        this.id = null;
      } else {
        this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.position = null;
      } else {
        if (this.position == null) {
          this.position = new com.datawhisperers.restfulexample.avromodel.PositionAvro();
        }
        this.position.customDecode(in);
      }

      this.speed = in.readDouble();

      if (in.readIndex() != 1) {
        in.readNull();
        this.timestampEpoch = null;
      } else {
        this.timestampEpoch = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.vehicleType = null;
      } else {
        this.vehicleType = in.readString(this.vehicleType instanceof Utf8 ? (Utf8)this.vehicleType : null);
      }

    } else {
      for (int i = 0; i < 8; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.accuracy = null;
          } else {
            this.accuracy = in.readString(this.accuracy instanceof Utf8 ? (Utf8)this.accuracy : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.activityType = null;
          } else {
            this.activityType = in.readString(this.activityType instanceof Utf8 ? (Utf8)this.activityType : null);
          }
          break;

        case 2:
          this.direction = in.readInt();
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.id = null;
          } else {
            this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.position = null;
          } else {
            if (this.position == null) {
              this.position = new com.datawhisperers.restfulexample.avromodel.PositionAvro();
            }
            this.position.customDecode(in);
          }
          break;

        case 5:
          this.speed = in.readDouble();
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.timestampEpoch = null;
          } else {
            this.timestampEpoch = in.readInt();
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.vehicleType = null;
          } else {
            this.vehicleType = in.readString(this.vehicleType instanceof Utf8 ? (Utf8)this.vehicleType : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










